### ISSUE TITLE
Problem - Sometimes it will get stuck on the first step

### ISSUE THREAD

**Issue by Jleagle** [mochman/node-red-contrib-light-transition#38]
### Terms

- [X] This request is not a duplicate of an existing issue.
- [X] I have provided as much information as I can to help resolve this issue.

#### Describe the problem.

Sometimes the node will get stuck on the first step, 1/60 etc. I have been testing this with inject nodes, stopping & starting the flow. Usually after less than 10 restarts it will get stuck. Not sure what's causing this or how to debug it.

### steps-to-reproduce

Start the flow, wait to see if it gets to 2/60,  stop the flow, restart.

### Actual Behavior

Occasionally it will just stop at 1/60.

### Version

1.7.2

### JSON of node setup

```shell
[
    {
        "id": "c9033972aae7ceeb",
        "type": "inject",
        "z": "ca7c0aaf4a7f4d79",
        "name": "07:15 Weekdays",
        "props": [
            {
                "p": "payload"
            },
            {
                "p": "topic",
                "vt": "str"
            }
        ],
        "repeat": "",
        "crontab": "15 07 * * 1,2,3,4,5",
        "once": false,
        "onceDelay": 0.1,
        "topic": "",
        "payload": "",
        "payloadType": "date",
        "x": 150,
        "y": 120,
        "wires": [
            [
                "08217238b8b75952"
            ]
        ]
    },
    {
        "id": "ed980b406fb48fbc",
        "type": "comment",
        "z": "ca7c0aaf4a7f4d79",
        "name": "Turn Alarm On",
        "info": "",
        "x": 130,
        "y": 80,
        "wires": []
    },
    {
        "id": "8770299df6eb1321",
        "type": "cast-to-client",
        "z": "ca7c0aaf4a7f4d79",
        "name": "1980s Zoom",
        "url": "https://samcloud.spacial.com/api/listen?sid=111415&rid=194939&f=mp3,any&br=128000,any&m=sc",
        "contentType": "audio/mpeg",
        "message": "",
        "language": "En-gb",
        "ip": "192.168.0.20",
        "port": "",
        "volume": "20",
        "x": 770,
        "y": 240,
        "wires": [
            []
        ]
    },
    {
        "id": "08217238b8b75952",
        "type": "api-current-state",
        "z": "ca7c0aaf4a7f4d79",
        "name": "Alarms On?",
        "server": "a3040d918205a56e",
        "version": 3,
        "outputs": 2,
        "halt_if": "on",
        "halt_if_type": "str",
        "halt_if_compare": "is",
        "entity_id": "input_boolean.work_alarm",
        "state_type": "str",
        "blockInputOverrides": false,
        "outputProperties": [
            {
                "property": "payload",
                "propertyType": "msg",
                "value": "",
                "valueType": "entityState"
            },
            {
                "property": "data",
                "propertyType": "msg",
                "value": "",
                "valueType": "entity"
            }
        ],
        "for": "0",
        "forType": "num",
        "forUnits": "minutes",
        "override_topic": false,
        "state_location": "payload",
        "override_payload": "msg",
        "entity_location": "data",
        "override_data": "msg",
        "x": 350,
        "y": 120,
        "wires": [
            [
                "e5315357aae72e70",
                "6c32572ef31f330e",
                "312e614528b8e525"
            ],
            []
        ]
    },
    {
        "id": "a6f3b48f3a164cb1",
        "type": "ha-button",
        "z": "ca7c0aaf4a7f4d79",
        "name": "",
        "version": 0,
        "debugenabled": false,
        "outputs": 1,
        "entityConfig": "70b810918fa3cbaa",
        "outputProperties": [
            {
                "property": "payload",
                "propertyType": "msg",
                "value": "",
                "valueType": "entityState"
            },
            {
                "property": "topic",
                "propertyType": "msg",
                "value": "",
                "valueType": "triggerId"
            },
            {
                "property": "data",
                "propertyType": "msg",
                "value": "",
                "valueType": "entity"
            }
        ],
        "x": 190,
        "y": 160,
        "wires": [
            [
                "08217238b8b75952"
            ]
        ]
    },
    {
        "id": "e5315357aae72e70",
        "type": "light-transition",
        "z": "ca7c0aaf4a7f4d79",
        "name": "",
        "startRGB": "#ff0000",
        "transitionRGB": "#ffc864",
        "endRGB": "#ffffff",
        "startMired": "",
        "endMired": "",
        "transitionTime": "5",
        "transitionTimeUnits": "Minute",
        "steps": "60",
        "startBright": "1",
        "endBright": "255",
        "brightnessType": "Integer",
        "transitionType": "Exponential",
        "colorTransitionType": "Weighted",
        "x": 550,
        "y": 120,
        "wires": [
            [
                "920b22cc663022ed"
            ],
            [
                "d162b174594aea67"
            ]
        ]
    },
    {
        "id": "d162b174594aea67",
        "type": "light-transition",
        "z": "ca7c0aaf4a7f4d79",
        "name": "",
        "startRGB": "#ff0000",
        "transitionRGB": "#ffc864",
        "endRGB": "#ffffff",
        "startMired": "",
        "endMired": "",
        "transitionTime": "10",
        "transitionTimeUnits": "Minute",
        "steps": "60",
        "startBright": "1",
        "endBright": "255",
        "brightnessType": "Integer",
        "transitionType": "Exponential",
        "colorTransitionType": "Weighted",
        "x": 800,
        "y": 180,
        "wires": [
            [
                "ec2bfa9cd58bd625"
            ],
            []
        ]
    },
    {
        "id": "920b22cc663022ed",
        "type": "api-call-service",
        "z": "ca7c0aaf4a7f4d79",
        "name": "Turn Floor On",
        "server": "a3040d918205a56e",
        "version": 5,
        "debugenabled": false,
        "domain": "light",
        "service": "turn_on",
        "areaId": [],
        "deviceId": [],
        "entityId": [
            "light.bedroom_floor_light"
        ],
        "data": "{\"brightness\": payload.brightness}",
        "dataType": "jsonata",
        "mergeContext": "",
        "mustacheAltTags": false,
        "outputProperties": [],
        "queue": "none",
        "x": 760,
        "y": 120,
        "wires": [
            []
        ]
    },
    {
        "id": "ec2bfa9cd58bd625",
        "type": "api-call-service",
        "z": "ca7c0aaf4a7f4d79",
        "name": "Turn Ceiling On",
        "server": "a3040d918205a56e",
        "version": 5,
        "debugenabled": false,
        "domain": "light",
        "service": "turn_on",
        "areaId": [],
        "deviceId": [],
        "entityId": [
            "light.shellydimmer2_48551900c175"
        ],
        "data": "{\"brightness\": payload.brightness}",
        "dataType": "jsonata",
        "mergeContext": "",
        "mustacheAltTags": false,
        "outputProperties": [],
        "queue": "none",
        "x": 1020,
        "y": 180,
        "wires": [
            []
        ]
    },
    {
        "id": "6c32572ef31f330e",
        "type": "function",
        "z": "ca7c0aaf4a7f4d79",
        "name": "",
        "func": "\n\nconsole.log(JSON.stringify(msg));\n\nreturn msg;",
        "outputs": 1,
        "noerr": 0,
        "initialize": "",
        "finalize": "",
        "libs": [],
        "x": 520,
        "y": 80,
        "wires": [
            []
        ]
    },
    {
        "id": "312e614528b8e525",
        "type": "random-output",
        "z": "ca7c0aaf4a7f4d79",
        "name": "",
        "outputs": 4,
        "useWeights": false,
        "weights": [
            "1",
            "1",
            "1",
            "1"
        ],
        "x": 580,
        "y": 240,
        "wires": [
            [
                "8770299df6eb1321"
            ],
            [
                "8770299df6eb1321"
            ],
            [
                "8770299df6eb1321"
            ],
            [
                "8770299df6eb1321"
            ]
        ]
    },
    {
        "id": "a3040d918205a56e",
        "type": "server",
        "name": "Home Assistant",
        "version": 2,
        "addon": false,
        "rejectUnauthorizedCerts": true,
        "ha_boolean": "y|yes|true|on|home|open",
        "connectionDelay": true,
        "cacheJson": true,
        "heartbeat": true,
        "heartbeatInterval": "60"
    },
    {
        "id": "70b810918fa3cbaa",
        "type": "ha-entity-config",
        "server": "a3040d918205a56e",
        "name": "node-red-alarm-on",
        "version": 2,
        "haConfig": [
            {
                "property": "name",
                "value": "Alarm On"
            },
            {
                "property": "icon",
                "value": ""
            },
            {
                "property": "device_class",
                "value": ""
            }
        ],
        "entityType": "button"
    }
]
```

**Comment by mochman** [comment]
Are you injecting the same thing when you see it freeze?  If so, what is the msg object that you are injecting?
How frequently are you injecting new parameters when you see it freeze?

**Comment by Jleagle** [comment]
Hey, just realised it doesn't just get stuck on the first step, node red crashes and the UI stops updating.

I am injecting the same data each time, by just pressing the inject node.

Here is the log of loading up node red and trying the flow above a few times until it crashes.

```
> node-red-docker@2.2.2 start /usr/src/node-red
> node $NODE_OPTIONS node_modules/node-red/red.js $FLOWS "--userDir" "/data"

20 Apr 14:44:52 - [warn] Projects disabled : editorTheme.projects.enabled=false
20 Apr 14:44:52 - [warn]

---------------------------------------------------------------------
Your flow credentials file is encrypted using a system-generated key.

If the system-generated key is lost for any reason, your credentials
file will not be recoverable, you will have to delete it and re-enter
your credentials.

You should set your own key using the 'credentialSecret' option in
your settings file. Node-RED will then re-encrypt your credentials
file using your chosen key the next time you deploy a change.
---------------------------------------------------------------------

20 Apr 14:45:15 - [red] Uncaught Exception:
20 Apr 14:45:15 - [error] TypeError: node.error is not a function
    at errorHandler (/data/node_modules/node-red-contrib-cast/cast-to-client.js:52:10)
    at getSpeechUrl (/data/node_modules/node-red-contrib-cast/cast-to-client.js:192:9)
    at Timeout._onTimeout (/data/node_modules/node-red-contrib-cast/cast-to-client.js:836:33)
    at listOnTimeout (internal/timers.js:559:11)
    at processTimers (internal/timers.js:500:7)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-red-docker@2.2.2 start: `node $NODE_OPTIONS node_modules/node-red/red.js $FLOWS "--userDir" "/data"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-red-docker@2.2.2 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /data/.npm/_logs/2022-04-20T13_45_15_210Z-debug.log
```

So actually looks like it's not a problem with light-transition, my bad.

**Comment by mochman** [comment]
Would you mind providing me with the msg that is being injected to the node?  I just want to make sure that my node isn't causing node-red to crash with some malformed node.error function call.

**Comment by Jleagle** [comment]
```
{
  "_msgid": "d655ab6bb850b927",
  "payload": "on",
  "topic": "",
  "data": {
    "entity_id": "input_boolean.work_alarm",
    "state": "on",
    "attributes": {
      "editable": true,
      "icon": "mdi:alarm-note",
      "friendly_name": "Work Alarm"
    },
    "last_changed": "2022-04-19T14:11:43.994674+00:00",
    "last_updated": "2022-04-19T14:11:43.994674+00:00",
    "context": {
      "id": "46d5da726769279f65543b1a663f6c9d",
      "parent_id": null,
      "user_id": null
    },
    "timeSinceChangedMs": 150892992,
    "original_state": "on"
  }
}
```

**Comment by Jleagle** [comment]
The whole flow:

![This is an image](https://i.imgur.com/ShmrWOu.png)

```
[
    {
        "id": "c9033972aae7ceeb",
        "type": "inject",
        "z": "ca7c0aaf4a7f4d79",
        "name": "07:15 Weekdays",
        "props": [
            {
                "p": "payload"
            },
            {
                "p": "topic",
                "vt": "str"
            }
        ],
        "repeat": "",
        "crontab": "15 07 * * 1,2,3,4,5",
        "once": false,
        "onceDelay": 0.1,
        "topic": "",
        "payload": "",
        "payloadType": "date",
        "x": 150,
        "y": 120,
        "wires": [
            [
                "08217238b8b75952"
            ]
        ]
    },
    {
        "id": "ed980b406fb48fbc",
        "type": "comment",
        "z": "ca7c0aaf4a7f4d79",
        "name": "Turn Alarm On",
        "info": "",
        "x": 130,
        "y": 80,
        "wires": []
    },
    {
        "id": "8770299df6eb1321",
        "type": "cast-to-client",
        "z": "ca7c0aaf4a7f4d79",
        "name": "1980s Zoom",
        "url": "https://samcloud.spacial.com/api/listen?sid=111415&rid=194939&f=mp3,any&br=128000,any&m=sc",
        "contentType": "audio/mpeg",
        "message": "",
        "language": "En-gb",
        "ip": "192.168.0.20",
        "port": "",
        "volume": "20",
        "x": 770,
        "y": 240,
        "wires": [
            []
        ]
    },
    {
        "id": "08217238b8b75952",
        "type": "api-current-state",
        "z": "ca7c0aaf4a7f4d79",
        "name": "Alarms On?",
        "server": "a3040d918205a56e",
        "version": 3,
        "outputs": 2,
        "halt_if": "on",
        "halt_if_type": "str",
        "halt_if_compare": "is",
        "entity_id": "input_boolean.work_alarm",
        "state_type": "str",
        "blockInputOverrides": false,
        "outputProperties": [
            {
                "property": "payload",
                "propertyType": "msg",
                "value": "",
                "valueType": "entityState"
            },
            {
                "property": "data",
                "propertyType": "msg",
                "value": "",
                "valueType": "entity"
            }
        ],
        "for": "0",
        "forType": "num",
        "forUnits": "minutes",
        "override_topic": false,
        "state_location": "payload",
        "override_payload": "msg",
        "entity_location": "data",
        "override_data": "msg",
        "x": 350,
        "y": 120,
        "wires": [
            [
                "e5315357aae72e70",
                "6c32572ef31f330e",
                "312e614528b8e525"
            ],
            []
        ]
    },
    {
        "id": "a6f3b48f3a164cb1",
        "type": "ha-button",
        "z": "ca7c0aaf4a7f4d79",
        "name": "",
        "version": 0,
        "debugenabled": false,
        "outputs": 1,
        "entityConfig": "70b810918fa3cbaa",
        "outputProperties": [
            {
                "property": "payload",
                "propertyType": "msg",
                "value": "",
                "valueType": "entityState"
            },
            {
                "property": "topic",
                "propertyType": "msg",
                "value": "",
                "valueType": "triggerId"
            },
            {
                "property": "data",
                "propertyType": "msg",
                "value": "",
                "valueType": "entity"
            }
        ],
        "x": 190,
        "y": 160,
        "wires": [
            [
                "08217238b8b75952"
            ]
        ]
    },
    {
        "id": "e5315357aae72e70",
        "type": "light-transition",
        "z": "ca7c0aaf4a7f4d79",
        "name": "",
        "startRGB": "#ff0000",
        "transitionRGB": "#ffc864",
        "endRGB": "#ffffff",
        "startMired": "",
        "endMired": "",
        "transitionTime": "5",
        "transitionTimeUnits": "Minute",
        "steps": "60",
        "startBright": "1",
        "endBright": "255",
        "brightnessType": "Integer",
        "transitionType": "Exponential",
        "colorTransitionType": "Weighted",
        "x": 550,
        "y": 120,
        "wires": [
            [
                "920b22cc663022ed"
            ],
            [
                "d162b174594aea67"
            ]
        ]
    },
    {
        "id": "d162b174594aea67",
        "type": "light-transition",
        "z": "ca7c0aaf4a7f4d79",
        "name": "",
        "startRGB": "#ff0000",
        "transitionRGB": "#ffc864",
        "endRGB": "#ffffff",
        "startMired": "",
        "endMired": "",
        "transitionTime": "10",
        "transitionTimeUnits": "Minute",
        "steps": "60",
        "startBright": "1",
        "endBright": "255",
        "brightnessType": "Integer",
        "transitionType": "Exponential",
        "colorTransitionType": "Weighted",
        "x": 800,
        "y": 180,
        "wires": [
            [
                "ec2bfa9cd58bd625"
            ],
            []
        ]
    },
    {
        "id": "920b22cc663022ed",
        "type": "api-call-service",
        "z": "ca7c0aaf4a7f4d79",
        "name": "Turn Floor On",
        "server": "a3040d918205a56e",
        "version": 5,
        "debugenabled": false,
        "domain": "light",
        "service": "turn_on",
        "areaId": [],
        "deviceId": [],
        "entityId": [
            "light.bedroom_floor_light"
        ],
        "data": "{\"brightness\": payload.brightness}",
        "dataType": "jsonata",
        "mergeContext": "",
        "mustacheAltTags": false,
        "outputProperties": [],
        "queue": "none",
        "x": 760,
        "y": 120,
        "wires": [
            []
        ]
    },
    {
        "id": "ec2bfa9cd58bd625",
        "type": "api-call-service",
        "z": "ca7c0aaf4a7f4d79",
        "name": "Turn Ceiling On",
        "server": "a3040d918205a56e",
        "version": 5,
        "debugenabled": false,
        "domain": "light",
        "service": "turn_on",
        "areaId": [],
        "deviceId": [],
        "entityId": [
            "light.shellydimmer2_48551900c175"
        ],
        "data": "{\"brightness\": payload.brightness}",
        "dataType": "jsonata",
        "mergeContext": "",
        "mustacheAltTags": false,
        "outputProperties": [],
        "queue": "none",
        "x": 1020,
        "y": 180,
        "wires": [
            []
        ]
    },
    {
        "id": "6c32572ef31f330e",
        "type": "function",
        "z": "ca7c0aaf4a7f4d79",
        "name": "",
        "func": "\n\nconsole.log(JSON.stringify(msg));\n\nreturn msg;",
        "outputs": 1,
        "noerr": 0,
        "initialize": "",
        "finalize": "",
        "libs": [],
        "x": 520,
        "y": 80,
        "wires": [
            []
        ]
    },
    {
        "id": "312e614528b8e525",
        "type": "random-output",
        "z": "ca7c0aaf4a7f4d79",
        "name": "",
        "outputs": 4,
        "useWeights": false,
        "weights": [
            "1",
            "1",
            "1",
            "1"
        ],
        "x": 580,
        "y": 240,
        "wires": [
            [
                "8770299df6eb1321"
            ],
            [
                "8770299df6eb1321"
            ],
            [
                "8770299df6eb1321"
            ],
            [
                "8770299df6eb1321"
            ]
        ]
    },
    {
        "id": "a3040d918205a56e",
        "type": "server",
        "name": "Home Assistant",
        "version": 2,
        "addon": false,
        "rejectUnauthorizedCerts": true,
        "ha_boolean": "y|yes|true|on|home|open",
        "connectionDelay": true,
        "cacheJson": true,
        "heartbeat": true,
        "heartbeatInterval": "60"
    },
    {
        "id": "70b810918fa3cbaa",
        "type": "ha-entity-config",
        "server": "a3040d918205a56e",
        "name": "node-red-alarm-on",
        "version": 2,
        "haConfig": [
            {
                "property": "name",
                "value": "Alarm On"
            },
            {
                "property": "icon",
                "value": ""
            },
            {
                "property": "device_class",
                "value": ""
            }
        ],
        "entityType": "button"
    }
]
```

**Comment by mochman** [comment]
I don't have most of those other nodes in my dev environment so I can't recreate it.  That's why I needed the msg that's sent to the `light-transition` node.  I tried injecting that message into my node repeatedly and I couldn't get node-red to crash.  

Relooking at your flow and node-red crash info, it looks like `node-red-contrib-cast` is what's throwing that error and causing node-red to crash on you.  Since the input to that isn't affected by the `light-transition` node, I don't think this is an issue 
 for this node anymore.
